=== damimotou/book/Java/other/specialist/XML/module_03/src/demo-1_2.xsd
<?xml version="1.0" encoding="UTF-8" ?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
    <xs:element name="personal">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="employee">
                    <xs:complexType>
                        <xs:all>
                            <xs:element name="phone" type="xs:string"/>
                            <xs:element name="email" type="xs:string"/>
                            <xs:element name="name">
                                <xs:complexType>
                                    <xs:sequence>
                                        <xs:element name="first" type="xs:string"/>
                                        <xs:element name="last" type="xs:string"/>
                                        <xs:element name="middle" type="xs:string"/>
                                    </xs:sequence>
                                </xs:complexType>
                            </xs:element>
                        </xs:all>
                    </xs:complexType>
                </xs:element>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
</xs:schema>

=== damimotou/book/specialist/XML/module_03/src/demo-1_2.xml
<?xml version="1.0" encoding="UTF-8" ?>
<personal xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
        xsi:noNamespaceSchemaLocation="demo-1_2.xsd">
    <employee>
        <phone>066-232-45-67</phone>
        <email>blabla@.bla.com</email>
        <name>
            <first>firstName</first>
            <last>lastName</last>
            <middle>middleName</middle>
        </name>
    </employee>
</personal>
