<?xml version="1.0" encoding="UTF-8" ?>
<!--<!DOCTYPE books SYSTEM "demo-3.dtd">-->
<!DOCTYPE books [
        <!ELEMENT books (book+)>
        <!ELEMENT book ((title, author+, price, publisher) | book+)>
        <!ELEMENT title (#PCDATA)>
        <!ELEMENT author (#PCDATA)>
        <!ELEMENT price (#PCDATA)>
        <!ELEMENT publisher (#PCDATA)>
        <!ENTITY bhv "BHV">
        <!ENTITY will "Williams">
        <!ENTITY apress "A-Press">
        ]>
<books>
    <book>
        <title>Название</title>
        <author>Автор</author>
        <price>123.00</price>
        <publisher>&apress;</publisher>
    </book>
    <book>
        <book>
            <title>Название</title>
            <author>Автор</author>
            <price>123.00</price>
            <publisher>&bhv;</publisher>
        </book>
        <book>
            <title>Название</title>
            <author>Автор</author>
            <price>123.00</price>
            <publisher>&will;</publisher>
        </book>
    </book>
</books>