=== damimotou/book/other/specialist/XML/module_03/src/demo-3_1.xsd
<?xml version="1.0" encoding="UTF-8" ?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">

    <xs:group name="personGroup">
        <xs:sequence>
            <xs:element name="id" type="xs:ID"/>
            <xs:element name="name" type="xs:string"/>
        </xs:sequence>
    </xs:group>

    <xs:complexType name="customerType">
        <xs:sequence>
            <xs:group ref="personGroup"/>
            <xs:element name="address" type="xs:string"/>
        </xs:sequence>
    </xs:complexType>

    <xs:complexType name="customersType">
        <xs:sequence>
            <xs:element name="customer" maxOccurs="unbounded" type="customerType"/>
        </xs:sequence>
    </xs:complexType>

    <xs:complexType name="clerkType">
        <xs:sequence>
            <xs:group ref="personGroup"/>
            <xs:element name="office" type="xs:string"/>
        </xs:sequence>
    </xs:complexType>

    <xs:complexType name="clerksType">
        <xs:sequence>
            <xs:element name="clerk" maxOccurs="unbounded" type="clerkType"/>
        </xs:sequence>
    </xs:complexType>

    <xs:element name="root">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="customers" type="customersType"/>
                <xs:element name="clerks" type="clerksType"/>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
</xs:schema>

=== damimotou/book/specialist/XML/module_03/src/demo-3.xml
<?xml version="1.0" encoding="UTF-8" ?>
<root xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
      xsi:noNamespaceSchemaLocation="demo-3_1.xsd">
    <customers>
        <customer>
            <id>id-1</id>
            <name>CustomerOne</name>
            <address>house #1</address>
        </customer>
        <customer>
            <id>id-2</id>
            <name>CustomerTwo</name>
            <address>house #2</address>
        </customer>
    </customers>
    <clerks>
        <clerk>
            <id>id-1</id>
            <name>ClerkOne</name>
            <office>office #1</office>
        </clerk>
        <clerk>
            <id>id-2</id>
            <name>ClerkTwo</name>
            <office>office #2</office>
        </clerk>
    </clerks>
</root>
